name: Publish Maven artifact to GitHub

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Maven deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '9'

      - name: Create settings.xml
        shell: bash
        run: |
          echo "<settings><servers><server><id>ossrh</id><username>" > settings.xml
          echo "${{ secrets.SONATYPE_USERNAME }}" >> settings.xml
          echo "</username><password>" >> settings.xml
          echo "${{ secrets.SONATYPE_PASSWORD }}" >> settings.xml
          echo "</password></server></servers></settings>" >> settings.xml

      - name: Import GPG key
        shell: bash
        run: |
          echo "${{ secrets.GPG_KEY }}" > betanzos-gpg.key
          gpg --pinentry-mode=loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" --import betanzos-gpg.key

      - name: Deploy Maven artifact
        shell: bash
        run: |
          mvn -e -B -s settings.xml deploy -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}"